### ISSUE TITLE
Resample, fill, and filter flight trajectories

### ISSUE THREAD

**Issue by mlshapiro** [contrailcirrus/pycontrails#51]
**Description**

We want to provide an opinionated, general set of methods for preparing flight trajectories for analysis.

Generally this includes:

- Resample trajectories to have a waypoint every ~ 10s - 1 min
- Interpolate spatial (lat, lon) gaps when upsampling. Interpolate small gaps linearly, interpolate longer gaps with geodesics.
- Filter the altitude signal to have an reasonable flight profile with distinct flight phases

Currently we have implemented `Flight.resample_and_fill` which works pretty well. This function contains some logic to validate an vertical profile, but the logic may be out of date. 

- [ ] If possible, make `resample_and_fill` a module function (`flight.resample_and_fill`) and call the module function from the class.

We also have a function [`flight.filter_altitude`](https://github.com/contrailcirrus/pycontrails/blob/main/pycontrails/core/flight.py#L1439) that should remove high frequency noise (usually ADS-B or FDR)  and snap cruise altitudes to 1000s of feet. This should be a cascade of filters with a (1) median filter (2) low pass filter (3) cruise altitude correction. Feel free to design a better methodology that applies to all the possible segment durations we may encounter.

- [x] Take `segment_duration` as an input to `filter_altitude`. In the class method version, we can calculate segment duration automatically
- [x] Create a class method `Flight.filter_altitude` that calls the module function
- [x] Design a set of filtering strategies that work with the set of altitude/segment duration inputs we may receive. Ideally we'll get data with a time interval of < 10s minutes. We may decide we can't filter higher interval data, so we can throw an error if the segment duration > 30 min or whatever starts to really fail.
- [x] Implement filtering strategy
- [x] Implement tests for (1) flight with very high frequency altitude data (segment_duration ~ 1s) (2) nominal frequency (segment_duration ~ 1min) (3) lower frequency (segment_duration ~ 10 min) (3) low frequency (like an ATC route string)

As a final step, confirm that the implementations of `resample_and_fill` and `filter_altitude` play well together. In the `Flight` class methods, we can make sure this is handled well. In the module functions, we can reference the input sources (e.g. `flight.segment_duration`) and suggest the best way to assemble cleaned trajectories.

- [x] Update the [Flight.ipynb](https://github.com/contrailcirrus/pycontrails/blob/main/docs/examples/Flight.ipynb) with an example of cleaning a trajectory

**Alternatives**

- Use the [traffic.core.flight.Flight.filter](https://traffic-viz.github.io/api_reference/traffic.core.flight.html#traffic.core.Flight.filter). This relies on the client side implementing the cascading filter. I'd prefer to implement an opinionated set of fliters that work best, and then raise warning/errors when we don't get good results

**Additional context**

- ~1s frequency (noisy) altitude measurement. [tests/unit/static/flight-spire-data-cleaning.pq](https://github.com/contrailcirrus/pycontrails/blob/main/tests/unit/static/flight-spire-data-cleaning.pq)
- ~1min frequency [tests/unit/static/flight.csv](https://github.com/contrailcirrus/pycontrails/blob/main/tests/unit/static/flight.csv)
- 1 min frequency: [tests/unit/static/flight-cocip2.csv](https://github.com/contrailcirrus/pycontrails/blob/main/tests/unit/static/flight-cocip2.csv)

**Comment by trdean1** [comment]
I went through existing methods with the provided test cases as well as some sample cases from Roger that have large gaps in the trajectory.  Some examples in [this notebook](https://github.com/contrailcirrus/admin/blob/main/snippets/2024-01-19-flight-fitting.ipynb) in the admin repo but it is a little messy.

In general, the existing `resample_and_fill` method works pretty well.  Smoothing flight data on top of this can be a little dangerous if you aren't careful.  If you have lower sample rates (e.g. every 1-5 minutes) then you will likely end up smoothing our step climbs/descents or adding artifacts at the start or end of cruise segments.

For noisy, high sample rate data (e.g. raw Spire data over land or FDR/QAR data), then some smoothing is warranted.  The [existing filtering method](https://github.com/contrailcirrus/pycontrails/blob/0f77764212ebbbed6530547761a2c23619afeb6c/pycontrails/core/flight.py#L1695) works pretty well in this case, but as seen in the notebook mentioned above, can introduce artifacts in climbs and descents. This can be resolved by only applying the smoothing on cruise segments (prototyped in the notebook). The [fit_altitude](https://github.com/contrailcirrus/pycontrails/blob/0f77764212ebbbed6530547761a2c23619afeb6c/pycontrails/core/flight.py#L941) method works extremely well for shorter flights with high sampling rates, but takes 10+ mins to run on long (6+ hr) flights.  A "low-pass filter", e.g. in the frequency domain, is not a good solution here because it's not going to be possible to avoid [ringing](https://en.wikipedia.org/wiki/Gibbs_phenomenon) when moving between flight phases.

My suggestions to close this out
- Remove the `fit_altitude` method based on piecewise linear fitting
- Update the existing `filter_altitude` method to only apply to cruise segments (prototyped in the example notebook)
- By default, apply `filter_altitude` to trajectories when the typical sample period is short (suggest median < 10 sec)
    - If the trajectory has large gaps but otherwise a short sample period, first resample and fill then apply `filter_altitude`. This will apply Roger's step-climb logic.
- For flights with larger sample periods, don't filter unless the user explicitly asks for it.

Other ideas that would require a bit more research:
- This might be a good candidate for a neural net approach to both clean and interpolate
- A kalman-filter-like approach that has some understanding of aircraft performance would be the most robust way to do this (rather than a naive low-pass filter), but also might be overkill

**Comment by trdean1** [comment]
More complete prototype [here](https://github.com/contrailcirrus/admin/blob/main/snippets/2024-01-22-flight-fitting-prototype.ipynb)
